accounts/urls.py
from . import views
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('profile/',views.profiles, name='profile'),
    path('dashboard', views.profile_dashboard, name='dashboard')
]

cart/urls.py
from . import views
from django.urls import path


app_name = 'cart'
urlpatterns = [
    path('',views.cart, name='cart'),
    path('shortcart/', views.cart_modal, name='cart_modal')
]

orders/urls.py
from . import views
from django.urls import path


app_name = 'orders'
urlpatterns = [
    path('',views.cart, name='cart'),
    path('update_item',views.update_item, name="update_item"),
    path('canvascontent', views.ajax_for_offcanvas, name='canvascontent'),
    path('checkout',views.checkout,name='checkout'),
    path('payment', views.payments, name='payment'),
    path('check-payment', views.check_payment, name='check-payment')
]

products/urls.py
from . import views
from django.urls import path


app_name = 'products'
urlpatterns = [
    # getting products
    path('',views.product, name='product'),
    path('formal/', views.formal_product, name="formal"),
    path('casual/', views.casual_product, name="casual"),
    path('sports/', views.sports_product, name="sports"),
    path('shoes/', views.shoes_product, name="shoes"),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    path("<int:pk>/", views.product_details, name="detail"),

    # wishlist
    path('wishlist/<int:product_id>/', views.wishlist, name='wishlist'),
    path('wishlist_products/', views.wishlist_products, name='wishlist-products'),
    path('wishlist/<int:product_id>/delete/', views.delete_wishlist_item, name='wishlist-delete')
]

website/urls.py
from . import views
from django.urls import path


app_name = 'website'
urlpatterns = [
    path('',views.home, name='home'),
    path('selectcurrency', views.select_currency, name="selectcurrency"),
    path('privacy', views.privacy, name='privacy'),
    path('terms', views.terms_of_use, name='terms')
]
    

templates/base/currency.html
<form id="currency_switcher" method="POST" action="{% url 'website:selectcurrency' %}">
  {% csrf_token %}
  <select name="currency" onchange="submit()">
    {% for curr in CURRENCIES %}
      <option value="{{ curr.code }}" {% if curr.code == request.session.currency %}selected="selected"{% endif %}>
        {{ curr.symbol }} , {{ curr.name }}
      </option>
    {% endfor %}
  </select>
  <noscript>
    <input type="submit" value="Set" />
  </noscript>
</form>

<!--
<form id="currency_switcher" method="POST" action="{% url 'currencies_set_currency' %}">{% csrf_token %}
    <select name="currency" onchange="$('#currency_switcher').submit()">
      {% for curr in CURRENCIES %}
        <option value="{{ curr.code }}" {% if curr.code == CURRENCY.code %}selected="selected"{% endif %}>
          {{ curr.symbol }} {{ curr.name }}
        </option>
      {% endfor %}
    </select>
    <noscript>
      <input type="submit" value="Set" />
    </noscript>
  </form>
-->

templates/base/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg" data-bs-theme="dark" style="background-color: #e33910">
    <div class="container-fluid">
      <button class="navbar-toggler me-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <a class="navbar-brand mx-auto ms-5 " href="/">
            <img src="{% static 'img/logo.jpg' %}" alt="4May logo" width="200" height="70">
        </a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mx-auto font-arial">
          <li class="nav-item px-3">
            <a class="nav-link" aria-current="page" data-category="F" href="{% url 'products:product' %}">All</a>
          </li>
          <li class="nav-item px-3">
            <a class="nav-link" aria-current="page" data-category="F" href="{% url 'products:formal' %}">Formal</a>
          </li>
          <li class="nav-item px-3">
            <a class="nav-link" data-category="C" href="{% url 'products:casual' %}">Casual</a>
          </li>
          <li class="nav-item px-3">
            <a class="nav-link" data-category="SH" href="{% url 'products:shoes' %}">Shoes</a>
          </li>
          <li class="nav-item px-3">
            <a class="nav-link" data-category="S" href="{% url 'products:sports' %}">Sports</a>
          </li>
        </ul>
      </div>
      <form class="d-flex" role="search">
        <div class="mx-lg-auto">

          <i class="bi bi-search text-light px-2 d-none" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="Top popover"></i>

          

{% if user.is_authenticated %}<span class="small text-white">Welcome: {{request.user}}</span>{% endif%}
          <a href="{% url 'accounts:profile' %}"><i class="bi bi-person text-light px-2"></i></a> 

          <i class="bi bi-bag text-light px-2 position-relative" type="button"  data-bs-toggle="offcanvas"  data-bs-target="#offcanvasCart" aria-controls="offcanvasCart">
            {% if cart_total != 0 %}
          <a class="btn" href="{% url 'orders:cart' %}">  <span class="badge small text-bg-light position-absolute top-100 start-50 translate-middle rounded-circle"
            id="updateCartTotal">{{cart_total}}</span>
          </a>
          {% endif %}
          </i>

          <div class="btn-group">
            <button  class="p-0" style="background-color:#e33910; border:none" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-three-dots-vertical text-light px-2"></i>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{% url 'products:wishlist-products' %}">
                <i class="bi bi-suit-heart"></i>&nbsp; Wish list
                <span class="float-end">{{wishlist_total}}</span></a> </li>
              <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#contactModal">
                <i class="bi bi-chat-right-quote"></i> &nbsp; Contact us</a></li>

                {% if request.user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'account_logout' %}">
                <i class="bi bi-power"></i> &nbsp; Logout</a>
              </li>
              {% endif %}
            </ul>
          </div>
        

        </div>
      </form>
    </div>
  </nav>



<!-- Modal -->
<div class="modal fade" id="contactModal" tabindex="-1" aria-labelledby="contactModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content text-center">
      <div class="modal-header">
        <h1 class="modal-title text-center fs-5" id="contactModalLabel">Contact us through</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <i class="bi bi-telephone text-center"></i>
        <p>+26378823934023</p>
        <hr>
        <i class="bi bi-whatsapp"></i>
        <p>+27789843673</p>
      </div>
      <div class="modal-footer text-center">
         <p class="small">Customer service is available from Monday to Friday 09:00 - 17:00</p>
      </div>
    </div>
  </div>
</div>

  <script type="text/javascript">
    //Navbar js
    let currentLocation = location.href;
    let navBarItem = document.getElementsByClassName('nav-link');

    for(let i = 0; i < navBarItem.length; i++){
        if(navBarItem[i].href == currentLocation){
            navBarItem[i].classList.add('active')
        }
        
    }
  </script>