cart/urls.py
from . import views
from django.urls import path


app_name = 'cart'
urlpatterns = [
    path('',views.cart, name='cart'),
    path('shortcart/', views.cart_modal, name='cart_modal')
]

orders/urls.py
from . import views
from django.urls import path


app_name = 'orders'
urlpatterns = [
    path('',views.cart, name='cart'),
    path('update_item',views.update_item, name="update_item"),
    path('canvascontent', views.ajax_for_offcanvas, name='canvascontent'),
    path('checkout',views.checkout,name='checkout'),
    path('payment', views.payments, name='payment'),
    path('check-payment', views.check_payment, name='check-payment')
]

products/urls.py
from . import views
from django.urls import path


app_name = 'products'
urlpatterns = [
    # getting products
    path('',views.product, name='product'),
    path('formal/', views.formal_product, name="formal"),
    path('casual/', views.casual_product, name="casual"),
    path('sports/', views.sports_product, name="sports"),
    path('shoes/', views.shoes_product, name="shoes"),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    path("<int:pk>/", views.product_details, name="detail"),

    # wishlist
    path('wishlist/<int:product_id>/', views.wishlist, name='wishlist'),
    path('wishlist_products/', views.wishlist_products, name='wishlist-products'),
    path('wishlist/<int:product_id>/delete/', views.delete_wishlist_item, name='wishlist-delete')
]

cart/models.py
from django.db import models

from orders.models import Order
from products.models import Product, Size, Color


class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, default='', null=True, blank=True)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, default='', null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.product.name
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total

orders/models.py
import uuid

from datetime import datetime
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail

from products.models import Product, ProductVariant


class Order(models.Model):
    """Order of the customer. Only one active at a time"""
    customer = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateField(auto_now=True)
    completed = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100, editable=False, unique=True)
    payment_status = models.CharField(max_length=200, blank=True, null=True)
    completed_date = models.DateField(blank=True, null=True)
    paynow_status = models.CharField(max_length=50, blank=True, null=True) 

    def __str__(self):
        return str(self.id)
    
    def complete_order(self, paynow_status):
        """Mark the order as completed and update necessary fields."""
        self.completed = True
        self.completed_date = datetime.now()
        self.paynow_status = paynow_status
        self.save()
    
    def save(self, *args, **kwargs):
        """Generate a transaction id for items without an id"""
        if not self.transaction_id:
            self.transaction_id = self.generate_transaction_id()
        super().save(*args, **kwargs)
    
    def send_order_completion_email(self):
        """Send an email notification to the user when the order is completed."""
        if self.customer and self.customer.email:
            subject = 'Order Completed Successfully'
            message = f'Hi {self.customer.first_name},\n\nYour order with transaction ID: {self.transaction_id} has been completed successfully.\n\n Thank you for shopping with 4May International!\n\n Yours faithful,\n\n 4May International sales team'
            from_email = settings.EMAIL_HOST_USER
            recipient_list = [self.customer.email]

            # Send the email
            try:
                send_mail(subject, message, from_email, recipient_list)
            except Exception as e:
                return e

    def generate_transaction_id(self):
        return str(uuid.uuid4())
    
    @property
    def get_cart_total(self):
        """Takes no args and returns the total amount in cart
        
        Returns:
            int: Total amount of items in the cart
        """
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        """Takes no args and returns the number of items in cart
        
        Returns:
            int: Total number of items in the cart 
        """
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    

class OrderItem(models.Model):
    """Represent items of an order i.e. items in a cart"""
    order = models.ForeignKey(Order, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    product_variant = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.IntegerField(default=0, blank=True, null=True)
    date_added = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.product.name
    
    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    
    @property
    def product_variant_size(self):
        return f'{self.product_variant.size.name}'
    
    @property
    def product_variant_color(self):
        return f'{self.product_variant.color.name}'

orders/forms.py
from django.forms import ModelForm
from address.models import ShippingAddress

class ShippingAddressForm(ModelForm):
    class Meta:
        fields = ['mobile_number','alternative_mobile_number','address', 'city', 'province', 'zipcode']
        model = ShippingAddress


class DeliveryMethodForm(ModelForm):
    class Meta:
        fields = ['pickup_instore', 'store']
        model = ShippingAddress

cart/views.py
import json
from django.shortcuts import render

from .models import Order
from products.models import Product

# Create your views here.
def cart(request):

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(   customer=customer, completed=False)
        items = order.cart_set.all()
        cartItems = order.get_cart_items
    else:
        try:
            cart = json.loads(request.COOKIES['cart'])
        except KeyError:
            cart = {}

        items = []
        order = {'get_cart_total':0, 'get_cart_items': 0}
        cartItems = order['get_cart_items']

        for i in cart:
            cartItems += cart[i]['quantity']

            product = Product.objects.get(id=i)
            total = (product.price * cart[i]['quantity'])

            order['get_cart_items'] += cart[i]['quantity']
            order['get_cart_total'] += total

            item = {
                'product':{
                    'id': product.id,
                    'name': product.name,
                    'price': product.price,
                    'image_url': product.image_url,
                },
                'quantity' : cart[i]['quantity'],
                'get_total' : total
            }
            items.append(item)


    context = {'items': items, 'order':order , 'cartItems': cartItems}
    return render(request, 'cart/cart_details.html', context)

def cart_modal(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(   customer=customer, completed=False)
        items = order.cart_set.all()
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items': 0}
    context = {'items': items, 'order':order }
    return render(request, 'cart/cart.html', context)

orders/views.py
import json

from decouple import config
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from paynow import Paynow

from address.models import ShippingAddress
from products.models import Product, ProductVariant
from .forms import ShippingAddressForm, DeliveryMethodForm
from .models import Order, OrderItem
from .utils import active_order, currency_session_value, process_payment


paynow = Paynow(
    config('INTEGRATION_ID', default=''), 
    config('INTEGRATION_KEY', default=''),
    config('PAYNOW_REQUEST_URL', default=''),
    config('PAYNOW_RESPONSE_URL', default='')
    )


@login_required
def cart(request):
    context = active_order(request)
    return render(request, 'orders/cart_details.html', context)

@login_required
def checkout(request):
    order_details = active_order(request)
    order = order_details['order']
    context = order_details
    user = request.user
    shipping_address = ShippingAddress(customer=user,order=order)
    form = ShippingAddressForm(request.POST or None, instance=shipping_address)
    pickup_form = DeliveryMethodForm(request.POST or None, instance=shipping_address)
    if pickup_form.is_valid():
        form_data = pickup_form.save(commit=False)
        if form_data.pickup_instore != False:
            form_data.save()
            pickup_form = DeliveryMethodForm()
            messages.success(request,'Thank you, we got your pickup point, proceed to order')
        elif form.is_valid():
            form.save()
            messages.success(request,'Thank you, we got your address, proceed to order')
            form = ShippingAddressForm()

    context.update({'form': form, 'pickup_form': pickup_form})
    return render(request, 'orders/checkout.html', context)   

@login_required
def update_item(request):
    '''Add or Removes items from the cart'''
    data = json.loads(request.body)
    product_id, action, variant_id  = data['productId'], data['action'], data['variantId']

    currency_session_value(request)

    product = get_object_or_404(Product,id=product_id)
    product_variant = get_object_or_404(ProductVariant, id=variant_id)
    order_details = active_order(request)
    order = order_details['order']
    # Creating cart item
    cartItem, created = OrderItem.objects.get_or_create(
        order=order, product=product, product_variant=product_variant
        )

    if action == 'add':
        cartItem.quantity = (cartItem.quantity + 1 )
    elif action == 'remove':
        cartItem.quantity = (cartItem.quantity - 1 )

    cartItem.save()
    # Pass filter in html
    price_with_currency = render_to_string(
        'orders/itemtotal.html', {'price': cartItem.get_total, 'curr': currency_session_value(request) }
        )
    grand_total_with_currency = render_to_string(
        'orders/itemtotal.html', {'price': cartItem.order.get_cart_total, 'curr': currency_session_value(request) }
        )
    un_serialised_data = {
        'price_with_currency': price_with_currency,
        'grand_total_with_currency': grand_total_with_currency,
        'quantity': cartItem.quantity, 
        'itemTotal': str(cartItem.get_total), 
        'grandTotal': str(cartItem.order.get_cart_total), 'cartTotal': cartItem.order.get_cart_items
        }
    # Delete item from cart is quantity is less than zero
    if cartItem.quantity <= 0:
        cartItem.delete()
        un_serialised_data = {
            'price_with_currency': price_with_currency,
            'grand_total_with_currency': grand_total_with_currency,
            'quantity': 0, 
            'itemTotal': 0, 
            'grandTotal': 0, 
            'cartTotal': 0
            }

    context = json.dumps(un_serialised_data)
    return JsonResponse(context, safe=False)

@login_required
def ajax_for_offcanvas(request):
    try:
        context = active_order(request)
        ajax_render = render_to_string('orders/offcanvas.html',{'items': context['items']})
        raw_data = {'ajax_render': ajax_render}
        data = json.dumps(raw_data)
        return JsonResponse(data, safe=False)
    except Exception as e:
        return e
    

@login_required
def payments(request):
    customer_order = active_order(request)
    items, order = customer_order.values()
    response = process_payment(paynow,items,order,request.user.email)

    if response.success:
        order.payment_status = response.poll_url
        order.save()
        return redirect(response.redirect_url)
    else:
        error_message = response.error
        messages.warning(request,f'Sorry, something went wrong with our payment partner, refresh & try again but you do not need to capture your address again. {error_message}')
        return redirect('orders:checkout')
        
@login_required
def check_payment(request):
    paynow_status = ("paid", "awaiting delivery", "delivered")
    order_details = active_order(request)
    order = order_details['order']
    current_order = Order.objects.get(id=order.id)
    status = paynow.check_transaction_status(order.payment_status)
    clean_status = (status.status).lower()

    if clean_status in paynow_status:
        try:
            current_order.complete_order(clean_status)
            messages.info(request, f'Transaction completed successfully, you paid {status.amount}')
            # Sending email to the user
            current_order.send_order_completion_email()
            return redirect('accounts:dashboard')
                    
        except Exception as e:
            messages.warning(request, f'Sorry we failed to update your order. Contact us please for a refund or order rectification.Error: {e}')
            return redirect('accounts:dashboard')            
                   
    else:
        error_message = status.status
        messages.warning(request, f'Transaction failed:  {error_message}. You may try again')
        return redirect('orders:checkout')

orders/templates/orders/cart.html
{% extends "base.html" %}
{% load static %}
{% load currency %}
{% block content %}
  
  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExampleRon" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title text-uppercase fw-bold" id="offcanvasExampleLabel">My Shopping cart</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>


    <div class="shadow-none p-3 bg-body-tertiary d-flex flex-wrap p-2">
        <h3> <i class="bi bi-truck"></i></h3>
        <p class="fw-light text-center">&nbsp;&nbsp; Delivery approx. 1-3 business days</p>
    </div>

    <div class="shadow-none p-3 mb-5 bg-body-secondary d-flex flex-wrap p-2">
        <h3> <i class="bi bi-check-circle-fill"   style="color:green;"></i></h3>
        <p class="fw-bold">&nbsp;GOOD CHOICE <br>
        <span class="small fw-normal">&nbsp;Your item was added to the shopping bag</span> </p> 
    </div>

    <div class="shadow-none p-3 mb-5 bg-body-tertiary d-flex flex-wrap p-2">
        <h3> <i class="bi bi-bag-x-fill"   style="color: black;"></i></h3>
        <p class="fw-bold">&nbsp;SHOP TO ADD ITEMS <br>
        <span class="small fw-normal">&nbsp;Your shopping bag is currently empty</span> </p> 
    </div>


    <div class="offcanvas-body">
        <div class="container">
            {% for item in items %}
            <div class="row">
                <hr>
                <div class="col-6">
                    <div class="card">
                        <img src="{{ item.product.image_url }}" alt="image">
                    </div>
                </div>
                <div class="col-6">
                    <h6 class="fw-bold">{{ item.product.name }}</h6>
                    <p>Color: {{ item.product_variant.color.name }} <br>
                    Size: {{ item.product_variant.size.name }} </p>
                    

                          <div class="d-inline-flex border rounded-1 border-black py-1 px-3 text-decoration-none mb-3">
                            <i id="myNegative" class="bi bi-dash"></i> &nbsp; {{ item.quantity }} &nbsp;<i id="myPositive" class="bi bi-plus"></i>
                          </div>
                          <p class="small fw-lighter float-end" >Unit price: {{ item.product.price|currency:request.session.currency }} {{ request.session.currency }} </p>
                        
                    <p class="small float-end">Total price: <span class="fw-bold"> {{ item.get_total|currency:request.session.currency }} {{ request.session.currency }} </span></p>
                </div>
            </div>
            {% endfor %}
        </div>
        <hr>
        <p>Total price: <span class="float-end"> {{ order.get_cart_total|currency:request.session.currency }} {{ request.session.currency }} </span> </p>
            <div class="shadow-none p-3 mb-5 bg-body-tertiary p-2 align-self-end w-100">
                <button class="btn btn-dark w-100 mb-2">Checkout </button>
                <button class="btn btn-outline-dark w-100 mb-2">Checkout </button>
            </div>



    </div>
  </div>
{% endblock content %}

orders/templates/orders/cart_details.html
{% extends "base.html" %}
{% load static %}
{% load currency %}
{% block content %}
<div class="container">

    <h1 class="display-6 fw-bold text-uppercase text-center mt-5 mb-5"> My Shopping cart</h1>

    <a href="{% url 'products:product' %}" class="btn btn-outline-primary mt-2 mb-3" ><i class="bi bi-arrow-left"></i> &nbsp;CONTINUE SHOPPING</a>
    <a href="{% url 'orders:checkout' %}" class="btn btn-outline-success mt-2 mb-3 float-end" >PROCEED TO CHECKOUT&nbsp;<i class="bi bi-arrow-right"></i></a>

    {% for item in items %}
    <div class="row">
        <div class="col-md-8">
            <div class="row">
                <div class="col-2">
                    <div class="card">
                        <img src="{{ item.product.image_url }}" alt="image">
                    </div>
                </div>
                <div class="col-10 align-content-center">
                    <h6 class="fw-bold text-uppercase">{{ item.product.name }}</h6>
                    <p>Color: {{ item.product_variant.color.name }}</p>
                    <p>Size: {{ item.product_variant.size.name }}</p>
                    <!--<p>VARIANT ID: {{ item.product_variant.id }}</p>-->

                    <!--For data passing to JS -->
                    <input type="hidden" id="size" value="{{ item.product_variant.id }}">
                    <input type="hidden" id="variantid" value="34">
                    <!--
                    <input type="hidden" id="variantid" value="{{ item.product_variant.id }}">-->



                    <div class="d-inline-flex border rounded-1 border-black py-1 px-3 text-decoration-none mb-3">

                        <i id="myNegative" class="bi bi-dash update-cart px-2" 
                        data-product="{{item.product.id}}" data-action="remove" data-variantId="{{ item.product_variant.id }}" ></i>

                        <span id='{{ item.product_variant.id }}updateText{{item.product.id}}'>{{ item.quantity }}</span>

                        <i id="myPositive" class="bi bi-plus update-cart px-2" data-product="{{item.product.id}}" data-action="add" data-variantId="{{ item.product_variant.id }}" ></i>
                    </div>

                    <p class="small fw-lighter float-end" >Unit price: {{ item.product.price|currency:request.session.currency }} {{ request.session.currency }}</p><br>
                        
                    <p class="small float-end">Total price: 
                        <span class="fw-bold" id="{{ item.product_variant.id }}updateTotal{{item.product.id}}"> {{ item.get_total|currency:request.session.currency }} {{ request.session.currency }} </span></p>
                </div>
            </div>
        </div>
        {% endfor %}
        <div class="col-md-4 px-2">
            <div class="card text-bg-light mx-3">
                <div class="card-body">
                    <p class="fw-bold">Cart item(s) total <span class="float-end" id="updateCartTotal">{{ order.get_cart_items}}</span> </p>
                  <p>DPD</p>
                  <p><i class="bi bi-truck"></i>&nbsp; <span class="small text-normal">Delivery approx is within 1 - 3 business days</span> </p>
                  <p class="fw-bold">Grand total <span class="float-end" id="updateGrandTotal"> {{ order.get_cart_total|currency:request.session.currency }} {{ request.session.currency }} </span> </p>
                </div>
              </div>
              <a class="btn btn-dark text-upppercase w-100 mx-3 mt-4 py-2" href="{% url 'orders:checkout' %}">Checkout</a>
        </div>
    </div>
    

</div>

{% endblock content %}

orders/templates/orders/checkout.html
{% extends "base.html" %}
{% load static %}
{% load currency %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="row">
        {% for msg in messages %}
        <div {% if msg.tags %} class="alert alert-{{msg.tags}}"{% endif %} role="alert">
            {{msg}}
        </div>
        {% endfor %}
        <div class="col-md-6 mt-5">
            <h6 class="fw-bold mb-5">Delivery details</h6>
            <div class="shadow p-3 mb-5 bg-body-tertiary rounded">
                <h6 class="text-center fw-bold">Delivery options</h6>
                <form method="POST" class="mt-5">
                    {% csrf_token %}
                    {{ pickup_form | crispy }}
                    <input id="pickupButton" class="btn btn-primary mt-2 d-none" type="submit" value="Save">
                </form>
                <p class="fst-italics small">Check this box if you want to do an instore pickup</p>
            </div>
        
        <div id="addressSection" class="shadow p-3 mb-5 bg-body-tertiary rounded d-block">
            <h6 class="text-center fw-bold">Delivery address & contact details</h6>
            <form method="POST">
                {% csrf_token %}
                {{form | crispy}}
                <input class="btn btn-primary mt-2" type="submit" value="Submit">
            </form>
        </div>

            <div class="shadow-lg p-3 mb-2 bg-body-tertiary rounded mt-5 w-50">
               <a id="paynowButton" class="btn" href="{% url 'orders:payment' %}"> <img class="img mt-2" src="{% static 'img/button_order_large.svg' %}" alt="orderbutton"></a>
               <div class="spinner-border text-info d-none float-end" id="loadPaynow" role="status"></div>
               <p class="small fst-italic">We use secure payment systems</p>
            </div>



        </div>



        
        <div class="col-md-6 mt-5">
            <h6 class="fw-bold text-center mb-5"> Order overview </h6>
            <p class="fw-bold"> {{ order.get_cart_total|currency:request.session.currency }} {{ request.session.currency }} <a class="float-end" href="{% url 'orders:cart' %}"><i class="bi bi-arrow-left-short"></i> &nbsp;Change order</a> </p>
            <hr>



            {% for item in items %}
                <div class="row">
                    <div class="col-md-4 mb-2">
                        <div class="card">
                            <img src="{{item.product.image_url}}" alt="image">
                        </div>
                    </div>
                

                    <div class="col-md-8">
                        <h6 class="fw-bold">{{ item.product.name }}</h6>
                        <p>Color: {{ item.product_variant.color.name }} <br>
                            Size: {{ item.product_variant.size.name }} <br>
                            Quantity: {{ item.quantity }}
                        </p>
                        
                        <p class="small fw-lighter float-end"> 
                            Unit price: {{ item.product.price|currency:request.session.currency }} {{ request.session.currency }}
                        </p>
                         <br>   
                        <p class="small float-end">Total price: <span class="fw-bold"> {{ item.get_total|currency:request.session.currency }} {{ request.session.currency }} </span>
                        </p>
                    </div>

                </div>
                {% endfor %}

                <hr>


                <div class="shadow-none p-3 mb-5 bg-body-tertiary p-2 align-self-end w-100">
                    <p class="small fw-lighter"> 
                        Delivery approx. 1 - 3 business days 
                    </p>
                    <p>Delivery fee: R20</p>
                    <p>
                        Your order: <span class="float-end">$ {{order.get_cart_total}}</span> 
                    </p>
                </div>




        </div>
    </div>
</div>



{% endblock content %}

orders/templates/orders/grandtotal.html
{% load static %}
{% load currency %}

{{ price|currency:curr }} {{ curr }}

orders/templates/orders/itemtotal.html
{% load static %}
{% load currency %}

{{ price|currency:curr }} {{ curr }}

orders/templates/orders/offcanvas.html
{% load static %}
{% load currency %}


<!-- part to put into offcanvas through Ajax  -->
<div class="container">
    <h5>OffCanvas adding things</h5>
    {% for item in items %}
        <div class="row">
            <hr>
            <div class="col-6">
                <div class="card">
                    <img src="{{ item.product.image_url }}" alt="image">
                </div>
            </div>
            <div class="col-6">
                <h6 class="fw-bold">{{ item.product.name }}</h6>
                <p>Color: {{ item.product_variant.color.name }} <br>
                Size: {{ item.product_variant.size.name }} </p>
                

                    <div class="d-inline-flex border rounded-1 border-black py-1 px-3 text-decoration-none mb-3">


                        <i id="myNegative" class="bi bi-dash update-cart px-2" 
                        data-product="{{item.product.id}}" data-action="remove" data-variantId="{{ item.product_variant.id }}" ></i>

                        <span id='{{ item.product_variant.id }}updateText{{item.product.id}}'>{{ item.quantity }}</span>

                        <i id="myPositive" class="bi bi-plus update-cart px-2" data-product="{{item.product.id}}" data-action="add" data-variantId="{{ item.product_variant.id }}" ></i>


                    </div>


            </div>
        </div>
    {% endfor %}
</div>
<!--END OFF CANVAS  -->