cart/urls.py
from . import views
from django.urls import path


app_name = 'cart'
urlpatterns = [
    path('',views.cart, name='cart'),
    path('shortcart/', views.cart_modal, name='cart_modal')
]

products/urls.py
from . import views
from django.urls import path


app_name = 'products'
urlpatterns = [
    # getting products
    path('',views.product, name='product'),
    path('formal/', views.formal_product, name="formal"),
    path('casual/', views.casual_product, name="casual"),
    path('sports/', views.sports_product, name="sports"),
    path('shoes/', views.shoes_product, name="shoes"),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    path("<int:pk>/", views.product_details, name="detail"),

    # wishlist
    path('wishlist/<int:product_id>/', views.wishlist, name='wishlist'),
    path('wishlist_products/', views.wishlist_products, name='wishlist-products'),
    path('wishlist/<int:product_id>/delete/', views.delete_wishlist_item, name='wishlist-delete')
]

website/urls.py
from . import views
from django.urls import path


app_name = 'website'
urlpatterns = [
    path('',views.home, name='home'),
    path('selectcurrency', views.select_currency, name="selectcurrency"),
    path('privacy', views.privacy, name='privacy'),
    path('terms', views.terms_of_use, name='terms')
]
    

templates/429.html
{% extends "allauth/layouts/entrance.html" %}
{% load allauth %}
{% block head_title %}
    Too Many Requests
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        Too Many Requests
    {% endelement %}
    <p>You are sending too many requests.</p>
{% endblock content %}

templates/base.html
{% load static %}
{% load currency %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>4May International</title>
        <meta name="description" content="The number one clothing shop for elegant people. We have dressed executives, musicians, TV presenters, footballer and many more. We have formal clothing, sports wear, shoes and casual clothes.">
        <link rel="canonical" href="https://4mayclothing.com/">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'img/logo.jpg' %}" style="height: 20px; width: 30px" type="image/x-icon">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/mainbutton.min.css' %}">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script type="text/javascript">

            let user = '{{ request.user }}'
            const baseUrl = "{% url 'products:wishlist' 0 %}"
            let baseUrlsplit = baseUrl.slice(0, -2);


            function getToken(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            const csrftoken = getToken('csrftoken');


            function getCookie(name){
                let cookieArr = document.cookie.split(';');


                for(let i=0; i < cookieArr.length; i++){
                    let cookiePair = cookieArr[i].split("=");

                    if(name == cookiePair[0].trim()){
                        return decodeURIComponent(cookiePair[1]);
                    }
                }

                return null;
            }
            let cart = JSON.parse(getCookie('cart'))
            

            if(cart == undefined){
                cart = {}
                console.log('Cart was created')
                document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
            }
            console.log('Cart', cart)

        </script>
    </head>
    <body>
        <div class="p-1 bg-black text-white">
            <div class="container d-flex justify-content-end">
            <span class="container small text-white fw-light">Selected currency: {{ request.session.currency }} </span>
            {% include 'base/currency.html' %}
            </div>
        </div>
        {% include 'base/navbar.html' %}
        {% block content %}{% endblock content %}
        <div class="container">
            <div class="row">
                <div class="col"></div>
                <div class="col"></div>
                <div class="col"></div>
            </div>
        </div>

            <footer class="py-3 my-4 bg-light text-dark">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3 small">
                  <li class="nav-item"><a href="{% url 'website:privacy' %}" class="nav-link px-2 text-black">Privacy statement</a></li>
                  <li class="nav-item"><a href="{% url 'website:terms' %}" class="nav-link px-2 text-black">Terms of use</a></li>
                </ul>
                <p class="text-center text-black small fw-bold d-flex justify-content-center">© 2024 4May International </p>
            </footer>

              <div class="container-fluid bg-light ">
                <span class="small fst-italics mb-1 px-2 float-end">Developed by: <a href="https://www.macronsynergy.co.zw">Macron Synergy (pvt) limited</a> </span>
              </div>



              <!-- Cookie Consent by FreePrivacyPolicy.com https://www.FreePrivacyPolicy.com -->
<script type="text/javascript" src="//www.freeprivacypolicy.com/public/cookie-consent/4.1.0/cookie-consent.js" charset="UTF-8"></script>
<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({"notice_banner_type":"simple","consent_type":"implied","palette":"dark","language":"en","page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],"notice_banner_reject_button_hide":false,"preferences_center_close_button_hide":false,"page_refresh_confirmation_buttons":false,"website_name":"www.4mayclothing.com","website_privacy_policy_url":"https://4Mayclothing.com/privacy"});
});
</script>

<noscript>Cookie Consent by <a href="https://www.freeprivacypolicy.com/">Free Privacy Policy Generator</a></noscript>
<!-- End Cookie Consent by FreePrivacyPolicy.com https://www.FreePrivacyPolicy.com -->





<!-- Below is the link that users can use to open Preferences Center to change their preferences. Do not modify the ID parameter. Place it where appropriate, style it as needed. -->


              <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
              <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
              <script type="text/javascript" src="{% static 'js/wishlist.js' %}"></script>
              <script type="text/javascript" src="{% static 'js/checkout.js' %}"></script>
              <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends "allauth/layouts/entrance.html" %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        4 May ecommerce
    {% endelement %}
    <p>Welcome to the ultimate shopping experience for 4May clothing.</p>
{% endblock content %}

templates/profile.html
{% extends "allauth/layouts/manage.html" %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        Your Profile
    {% endelement %}
    <p>Welcome to your profile {{ request.user }}</p>
    <p>Use this profile to manage your account you can do account management and do things that are important to you.</p>
{% endblock content %}