cart/urls.py
from . import views
from django.urls import path


app_name = 'cart'
urlpatterns = [
    path('',views.cart, name='cart'),
    path('shortcart/', views.cart_modal, name='cart_modal')
]

orders/urls.py
from . import views
from django.urls import path


app_name = 'orders'
urlpatterns = [
    path('',views.cart, name='cart'),
    path('update_item',views.update_item, name="update_item"),
    path('canvascontent', views.ajax_for_offcanvas, name='canvascontent'),
    path('checkout',views.checkout,name='checkout'),
    path('payment', views.payments, name='payment'),
    path('check-payment', views.check_payment, name='check-payment')
]

products/urls.py
from . import views
from django.urls import path


app_name = 'products'
urlpatterns = [
    # getting products
    path('',views.product, name='product'),
    path('formal/', views.formal_product, name="formal"),
    path('casual/', views.casual_product, name="casual"),
    path('sports/', views.sports_product, name="sports"),
    path('shoes/', views.shoes_product, name="shoes"),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    path("<int:pk>/", views.product_details, name="detail"),

    # wishlist
    path('wishlist/<int:product_id>/', views.wishlist, name='wishlist'),
    path('wishlist_products/', views.wishlist_products, name='wishlist-products'),
    path('wishlist/<int:product_id>/delete/', views.delete_wishlist_item, name='wishlist-delete')
]

website/urls.py
from . import views
from django.urls import path


app_name = 'website'
urlpatterns = [
    path('',views.home, name='home'),
    path('selectcurrency', views.select_currency, name="selectcurrency"),
    path('privacy', views.privacy, name='privacy'),
    path('terms', views.terms_of_use, name='terms')
]
    

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.safestring import mark_safe


class Category(models.Model):
    CATEGORY_CLASSES = [
        ('F', 'Formal'),
        ('C', 'Casual'),
        ('S', 'Sports'),
        ('SH', 'Shoes'),
    ]
    name = models.CharField(max_length=2,choices=CATEGORY_CLASSES,default="F")

    class Meta:
        verbose_name = "Categorie"

    def __str__(self):
        return self.name


class Size(models.Model):
    ''' Size model to allow addition of new sizes '''
    name = models.CharField(max_length=4, blank=True, null=True)

    def __str__(self):
        return self.name


class Color(models.Model):
    """All available colors in the system"""
    name = models.CharField(max_length=200, blank=True, null=True)
    code = models.CharField(max_length=7, blank=True, null=True)

    def color_tag(self):
        if self.code is not None:
            return mark_safe(f'<p style="background-color:{self.code}">color</p>')
        else:
            return ""

    def __str__(self):
        return self.name


class Product(models.Model):
    """Product has a list of products in our inventory"""
    CATEGORY_CLASSES = [
        ('F', 'Formal'),
        ('C', 'Casual'),
        ('S', 'Sports'),
        ('SH', 'Shoes'),
    ]

    VARIANTS = [
        ('Size', 'Size'),
        ('Color', 'Color'),
        ('Size-Color', 'Size-Color'),
    ]
    name = models.CharField(max_length=200, blank=False, null=False)
    description = models.CharField(max_length=200, blank=True, null=True)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=6)
    category = models.CharField(
        max_length=2, choices=CATEGORY_CLASSES, default="F"
        )
    variant = models.CharField(
    max_length=10, choices=VARIANTS, default="None"
    )
    image = models.ImageField(upload_to='uploads/product/',null=True,blank=True)

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):
        return reverse("products:detail", kwargs={"pk": self.pk})
    
    
    @property
    def image_url(self):
        try:
            url = self.image.url
        except ValueError:
            url = ''
        return url
    
    def image_tag(self):
        if self.image_url != '':
            return mark_safe(f'<img src="{self.image_url}" height="50" />')
        else:
            return ''


class ProductVariant(models.Model):
    """Variant of the product. i.e. Size, Color or both"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE, blank=True, null=True)
    size = models.ForeignKey(Size, on_delete=models.CASCADE, blank=True, null=True)          

    def __str__(self):
        return f"{self.product.name}"
    

class WishList(models.Model):
    """Items that the users was to buy later"""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.product.name}" 

products/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseServerError
from django.shortcuts import get_object_or_404, render, redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy

from .models import Product, ProductVariant, WishList
from orders.utils import active_order


def product(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request,'products/product_list.html', context)

def formal_product(request):
    products = Product.objects.filter(category="F")
    context = {'products': products}
    return render(request,'products/formal.html', context)

def casual_product(request):
    products = Product.objects.filter(category="C")
    context = {'products': products}
    return render(request,'products/casual.html', context)

def sports_product(request):
    products = Product.objects.filter(category="S")
    context = {'products': products}
    return render(request,'products/sports.html', context)

def shoes_product(request):
    products = Product.objects.filter(category="SH")
    context = {'products': products}
    return render(request,'products/shoes.html', context)

def product_details(request, pk):
    if not request.session.has_key('currency'):
        request.session['currency'] = settings.DEFAULT_CURRENCY

    context = active_order(request)
    product = get_object_or_404(Product, pk=pk)
    context.update({'product': product})

    if product.variant != 'None':
        if request.method == 'POST': #if we select color
            variant_id = request.POST.get('variantid')
            variant = ProductVariant.objects.get(id=variant_id)
            colors = ProductVariant.objects.filter(product_id=pk,size_id=variant.size_id )
            size = ProductVariant.objects.raw('SELECT * FROM  products_productvariant  WHERE product_id=%s GROUP BY size_id',[pk])
        else:
            variants = ProductVariant.objects.filter(product_id=pk)
            colors = ProductVariant.objects.filter(
                product_id=product.id, 
                size_id=variants[0].size_id
                )
            size = ProductVariant.objects.raw(
                'SELECT * FROM products_productvariant WHERE product_id=%s GROUP BY size_id',[pk]
                )
            variant = ProductVariant.objects.get(id=variants[0].id)
        context.update({'colors': colors, 'variant': variant, 'sizes': size})

    return render(request, 'products/details.html', context)


def ajaxcolor(request):
    data = {}
    if request.POST.get('action') == 'post':
        size_id = request.POST.get('size')
        productid = request.POST.get('productid')
        colors = ProductVariant.objects.filter(product_id=productid, size_id=size_id)
        context = {
            'size_id': size_id,
            'productid': productid,
            'colors': colors,
        }
        data = {'rendered_table': render_to_string('products/color_list.html', context=context)}
        return JsonResponse(data)
    return JsonResponse(data)

@login_required
def wishlist_products(request):
    user = request.user
    wishlist_products = WishList.objects.filter(user=user)
    context = {'wishlist_products': wishlist_products }
    return render(request, 'products/wishlist.html',context)

@login_required
def wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    wishlist_item, created = WishList.objects.get_or_create(user=request.user, product=product)

    if not created:
        wishlist_item.delete()
        added_to_wishlist = False
    else:
        added_to_wishlist = True

    return JsonResponse({'added_to_wishlist': added_to_wishlist})

@login_required
def delete_wishlist_item(request, product_id):
    wishlist_item = get_object_or_404(WishList,product_id=product_id)

    try:
        if wishlist_item.user != request.user:
            return HttpResponseForbidden()
        else:
            wishlist_item.delete()
            return redirect('products:wishlist-products')

    except Exception as e:
        return HttpResponseServerError( f'{e} An error occurred while trying to delete the item.')

products/templates/products/casual.html
{% extends "base.html" %}
{% load static %}
{% load currency %}
{% load wishlist_tags %}

{% block content %}
<div class="formalbg-img"></div>

<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-6 offset-3 d-flex justify-content-center ">
            <h1 class="display-6 text-uppercase fw-bold">
                Men's Casual Outfits</h1>
        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="row d-flex align-items-lg-stretch">
        {% for product in products %}
        <div class="col-md-4 mb-3">

            <div class="card">
                <img class="card-img-top" src="{{ product.image_url }}" alt="image">
                <div class="card-img-overlay">
                    {% if user.is_authenticated %}
                        <div class="float-end icon-circle ">
                            <i class="bi bi-suit-heart-fill  wish-icon 
                                {% if request.user|in_wishlist:product %}
                                filled
                                {% endif %}" data-product-id="{{ product.id }}">
                            </i>
                        </div>
                    {% endif %}

                    <a href="{{ product.get_absolute_url }}">
                        <div class="card-overlay fw-smaller">Click to shop</div>
                    </a>

                    <div class="d-flex align-items-end h-100">
                        <img class="float-start img-fluid" 
                        src="{% static 'img/logo.jpg' %}" alt="4May logo" width="70" height="40">
                    </div>

                </div>
            </div>
            
            <h5 class="mt-2">{{ product.name }}</h5>
            <p class="fw-bold">{{ product.price|currency:request.session.currency }} {{ request.session.currency }}</p>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

products/templates/products/color_list.html
<input class="form-control" type="hidden" name="size" id="size" value="{{ size_id }}"> 

<ul>
    {% for c in colors %}
    <div class="form-check form-check-inline">

        <input class="form-check-input" type="radio"  {% if variant.id == c.id %} checked {% endif %} name="variantid" id="variantid" value="{{ c.id }}" onchange="this.form.submit();" >

            <label class="form-check-label" for="inlineRadio1" style="background-color: {{ c.color.code }} ; color:antiquewhite">
                &nbsp;{{ c.color.name }}&nbsp;

            </label>
    </div>
    {% endfor %}
</ul>

products/templates/products/details.html
{% extends "base.html" %}
{% load static %}
{% load currency %}
{% load wishlist_tags %}

{% block content %}

<!-- OFF CANVAS START -->
 {% if user.is_authenticated %}
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasCart" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h6 class="offcanvas-title text-uppercase fw-bold d-flex me-5" id="offcanvasCartLabel">My Shopping cart</h6>
      <a href="{% url 'orders:cart' %}">
      <span class="small fw-normal justify-content-end ms-4">SEE DETAILS</span></a>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button> 
    </div>


    <div class="shadow-none p-3 bg-body-tertiary d-flex flex-wrap p-2">
        <h3> <i class="bi bi-truck"></i></h3>
        <p class="fw-light text-center">&nbsp;&nbsp; Delivery approx. 1-3 business days</p>
    </div>



    <div id="cart-not-empty" class="shadow-none p-3 mb-5 bg-body-secondary d-flex flex-wrap p-2 d-none">
        <h3> <i class="bi bi-check-circle-fill"   style="color:green;"></i></h3>
        <p class="fw-bold">&nbsp;GOOD CHOICE <br>
        <span class="small fw-normal">&nbsp;Your item was added to the shopping bag</span> </p> 
    </div>
    {% if order.get_cart_total == 0 %}
    <div id="cart-is-empty" class="shadow-none p-3 mb-5 bg-body-tertiary d-flex flex-wrap p-2">
        <h3> <i class="bi bi-bag-x-fill"   style="color: black;"></i></h3>
        <p class="fw-bold">&nbsp;SHOP TO ADD ITEMS <br>
        <span class="small fw-normal">&nbsp;Your shopping bag is currently empty</span> </p> 
    </div>
    {% endif %}



    <div class="offcanvas-body">
        <!--The start of ajax append -->
        <div id="ajaxrefresh"> 
            <div class="container">
            {% for item in items %}
                <div class="row">
                    <hr>
                    <div class="col-6">
                        <div class="card">
                            <img src="{{ item.product.image_url }}" alt="image">
                        </div>
                    </div>
                    <div class="col-6">
                        <h6 class="fw-bold">{{ item.product.name }}</h6>
                        <p>Color: {{ item.product_variant.color.name }} <br>
                        Size: {{ item.product_variant.size.name }} </p>
                        

                            <div class="d-inline-flex border rounded-1 border-black py-1 px-3 text-decoration-none mb-3">


                                <i id="myNegative" class="bi bi-dash update-cart px-2" 
                                data-product="{{item.product.id}}" data-action="remove" data-variantId="{{ item.product_variant.id }}" ></i>

                                <span id='{{ item.product_variant.id }}updateText{{item.product.id}}'>{{ item.quantity }}</span>

                                <i id="myPositive" class="bi bi-plus update-cart px-2" data-product="{{item.product.id}}" data-action="add" data-variantId="{{ item.product_variant.id }}" ></i>


                            </div>


                            <p class="small fw-lighter float-end" >Unit price: {{ item.product.price|currency:request.session.currency }} {{ request.session.currency }} </p>
                            
                            <p class="small float-end">Total price: 
                                <span class="fw-bold" id="{{ item.product_variant.id }}updateTotal{{item.product.id}}"> {{ item.get_total|currency:request.session.currency }} {{ request.session.currency }}</span>
                            </p>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div> 
        <!--The end of ajax append -->

        <hr>
        <p class="fw-bold">Total items <span class="float-end" id="updateCartTotal">{{ order.get_cart_items }}</span> 
        </p>

        <p class="fw-bold">Grand total <span class="float-end" id="updateGrandTotal"> {{ order.get_cart_total|currency:request.session.currency }} {{ request.session.currency }} </span> 
        </p>


        <div class="shadow-none p-3 mb-5 bg-body-tertiary p-2 align-self-end w-100">
                <a class="btn btn-outline-dark w-100" href="{% url 'orders:checkout' %}">Checkout</a>
        </div>
    </div>
</div>
<!--END OFF CANVAS  -->

{% endif %}




<!--Product details  -->
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <img src="{{ product.image_url }}">
                <div class="card-img-overlay d-flex justify-content-end">

                    {% if user.is_authenticated %}
                    <div class="float-end icon-circle ">
                        <i class="bi bi-suit-heart-fill  wish-icon 
                            {% if request.user|in_wishlist:product %}
                            filled
                            {% endif %}" data-product-id="{{ product.id }}">
                        </i>
                    </div>
                {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-1"></div>


        <div class="col-md-4 mt-3 bg-light">
            <div class="d-flex mt-3 mb-3">
                <div class="align-self-end">
                    <p class="fw-light small"> <a href="{% url 'website:home' %}">Home</a> / <a href="{% url 'products:product' %}">Formal</a> </p>
                </div>

                <div class="ms-auto p-2">
                    <img class="img-fluid" src="{% static 'img/Logo.jpg' %}" alt="4May logo" width="130" height="50">
                </div>
            </div>
            <div class="mt-5">
                <h2 class="fw-bold text-uppercase">{{ product.name }}</h2>
                <p class="fw-bold mt-3"> {{ product.price|currency:request.session.currency }} {{ request.session.currency }} <span class="fw-light small">&nbsp; Price Incl. Tax</span></p>
            </div>

            <script>
                $(document).on('change', '#post-size',function(e){
                    e.preventDefault();
                    $.ajax({
                        type:'POST',
                        url:'{% url "products:ajaxcolor" %}',
                        data:{
                            productid:$('#productid').val(),
                            size:$('#size').val(),
                            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                            action: 'post'
                        },
                        data_type : 'html',
                        success: function (data) {
                            console.log("success");
                            $('#appendHere').html(data.rendered_table);
                        },
                        error: function (data) {
                            alert("Well this happens in tech. Something went wrong. Refresh and try again. " + data);
                        }
                    });
                });
            </script>



        <div class="product-btn mb-5">   
            {% if product.variant == 'Size-Color' %}
            <div class="size-option">
                <form method="POST" id="post-size" action="">
                    <input class="form-control" type="hidden" name="productid" id="productid" aria-label="product id" value="{{ product.id }}">

                    <p class="text-uppercase fw-bold small">Select Size</p>
                    {% csrf_token %}
                    <select class="form-select form-select-sm mb-3 text-center w-50"     aria-label="Size" name="size" id="size">
                        {% for sz in sizes %}
                        <option {% if variant.size_id == sz.size_id %} selected {% endif %} value="{{ sz.size_id }}">{{ sz.size.name }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>

            

            <div class="color-option">
                <form method="post" action="" id="post-color">
                    <p class="text-uppercase fw-bold">Select Colour</p>
                    {% csrf_token %}
                    <div id="appendHere">
                        <input class="form-control" type="hidden" name="size" id="size" value="{{ size_id }}"> 
                        <ul>
                            {% for c in colors %} 
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio"  {% if variant.id == c.id %} checked {% endif %} name="variantid" id="variantid" value="{{variant.id}}" onchange="this.form.submit();">
                                <label class="form-check-label" for="inlineRadio1" style="color:antiquewhite; background-color: {{ c.color.code }} ">
                                    &nbsp;{{ c.color.name }}&nbsp;
                                </label>
                            </div>
                            {% endfor %}
                        </ul>
                    </div>
                </form>  
            </div>

            {% elif product.variant == 'Size' %}

            <div class="size-option">
                <form method="POST" id="post-size" action="">
                    <input class="form-control" type="hidden" name="productid" id="productid" aria-label="product id" value="{{ product.id }}">
                    <input class="form-control" type="hidden" name="productid" id="variantid" aria-label="variantid" value="{{ variant.id }}">

                    {% csrf_token %}
                    <select class="form-select mb-3 text-center w-50 form-select-sm"     aria-label="Size">
                        {% for sz in sizes %}
                        <option {% if variant.size_id == sz.size_id %} selected {% endif %} value="{{ sz.size_id }}" name="size" id="size">{{ sz.size.name }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>

            {% elif product.variant == 'Color' %}

            <div class="color-option">
                <form method="POST" id="post-color">
                        {% csrf_token %}
                    <div id="appendHere">
                        <input class="form-control" type="hidden" name="size" id="size" value="{{ size_id }}"> 

                        <ul>
                            {% for c in colors %}
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio"  {% if variant.id == c.id %} checked {% endif %} name="variantid" id="variantid" value="{{variant.id}}" onchange="this.form.submit();">
                                <label class="form-check-label" for="inlineRadio1" style=" color:antiquewhite; background-color : {{ c.color.code }}" >&nbsp;{{ c.color.name }}&nbsp;</label>
                            </div>
                            {% endfor %}
                        </ul>
                    </div>
                </form>  
            </div>
            {% endif %}
        </div>

            <p> <span class="fw-light small">&nbsp; Delivery approx. 1 -3 business days 
            </span></p>
    
            {% if user.is_authenticated %}
            <button id="offcanvas-ajax" class="btn btn-success update-cart w-100" type="button" data-product="{{ product.id }}" data-action="add" data-variantId="{{ variant.id }}" data-buttonclicked="yes" data-bs-toggle="offcanvas" data-bs-target="#offcanvasCart" aria-controls="offcanvasCart">
                ADD TO CART
            </button>
            {% else %}
            <a href="{% url 'orders:update_item' %}" class="btn btn-success">ADD TO CART</a>
            {% endif %}

          
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
<!--Product details  -->


{% endblock %}

products/templates/products/formal.html
{% extends "base.html" %}
{% load static %}
{% load currency %}
{% load wishlist_tags %}

{% block content %}
<div class="formalbg-img"></div>

<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-6 offset-3 d-flex justify-content-center ">
            <h1 class="display-6 text-uppercase fw-bold">
                Men's Formal Outfits</h1>
        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="row d-flex align-items-lg-stretch">
        {% for product in products %}
        <div class="col-md-4 mb-3">
            <div class="card">

                <img class="card-img-top" src="{{ product.image_url }}" alt="image">
                <div class="card-img-overlay">

                    {% if user.is_authenticated %}
                        <div class="float-end icon-circle ">
                            <i class="bi bi-suit-heart-fill  wish-icon 
                                {% if request.user|in_wishlist:product %}
                                filled
                                {% endif %}" data-product-id="{{ product.id }}">
                            </i>
                        </div>
                    {% endif %}

                    <a href="{{ product.get_absolute_url }}">
                        <div class="card-overlay fw-smaller">Click to shop</div>
                    </a>

                    <div class="d-flex align-items-end h-100">
                        <img class="float-start img-fluid" src="{% static 'img/logo.jpg' %}" alt="4May logo" width="70" height="40">
                    </div>

                </div>
            </div>
            <h5 class="mt-2">{{ product.name }}</h5>
            <p class="fw-bold">{{ product.price|currency:request.session.currency }} {{ request.session.currency }}</p>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

products/templates/products/product_list.html
{% extends "base.html" %}
{% load static %}
{% load currency %}
{% currency_context %}
{% load wishlist_tags %}

{% block content %}
<script>
    function toggleWishList(element) {
        element.classList.toggle('filled');
    }
</script>
<div class="bg-img"></div>

<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-4 offset-4 d-flex justify-content-center ">
            <h1 class="display-6 text-uppercase fw-bold">
                Men's Outfits</h1>
        </div>
    </div>
</div>


<div class="container">
    <div class="row d-flex align-items-lg-stretch">
        {% for product in products %}
        <div class="col-md-4 mb-3">
            
            <div class="card">

                <img class="card-img-top" src="{{ product.image_url }}" alt="image">
                <div class="card-img-overlay">
                    {% if user.is_authenticated %}
                        <div class="float-end icon-circle ">
                            <i class="bi bi-suit-heart-fill  wish-icon 
                                {% if request.user|in_wishlist:product %}
                                filled
                                {% endif %}" data-product-id="{{ product.id }}">
                            </i>
                        </div>
                    {% endif %}

                    <a href="{{ product.get_absolute_url }}">
                        <div class="card-overlay fw-smaller">Click to shop</div>
                    </a>
                    <div class="d-flex align-items-end h-100">
                        <img class="float-start img-fluid" src="{% static 'img/Logo.jpg' %}" alt="4May logo" width="70" height="40">
                    </div>

                </div>
            </div>
            
            <h5 class="mt-2">{{ product.name }} </h5>
            <p class="fw-bold">{{ product.price|currency:request.session.currency }} {{ request.session.currency }}</p>
            
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

products/templates/products/shoes.html
{% extends "base.html" %}
{% load static %}
{% load currency %}
{% load wishlist_tags %}

{% block content %}
<div class="shoesbg-img"></div>

<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-4 offset-4 d-flex justify-content-center ">
            <h1 class="display-6 text-uppercase fw-bold">
                Men's Shoes</h1>
        </div>
    </div>
</div>


<div class="container-fluid">
    <div class="row d-flex align-items-lg-stretch">
        {% for product in products %}
        <div class="col-md-4 mb-3">
            <div class="card">

                <img class="card-img-top" src="{{ product.image_url }}" alt="image">
                <div class="card-img-overlay">
                    {% if user.is_authenticated %}
                        <div class="float-end icon-circle ">
                            <i class="bi bi-suit-heart-fill  wish-icon 
                                {% if request.user|in_wishlist:product %}
                                filled
                                {% endif %}" data-product-id="{{ product.id }}">
                            </i>
                        </div>
                    {% endif %}


                    <a href="{{ product.get_absolute_url }}">
                        <div class="card-overlay fw-smaller">Click to shop</div>
                    </a>


                    <div class="d-flex align-items-end h-100">
                        <img class="float-start img-fluid" src="{% static 'img/logo.jpg' %}" alt="4May logo" width="70" height="40">
                    </div>

                </div>
            </div>
            <h5 class="mt-2">{{ product.name }}</h5>
            <p class="fw-bold">{{ product.price|currency:request.session.currency }} {{ request.session.currency }}</p>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

products/templates/products/wishlist.html
{% extends "base.html" %}
{% load static %}
{% load currency %}

{% block content %}
<div class="container">
    <h1 class="Display-4 fw-bold text-uppercase mb-5 mt-5 text-center">My Wishlist</h1>

    <a href="{% url 'products:product' %}"> <button class="btn btn-outline-dark mb-5"><i class="bi bi-arrow-left"></i> &nbsp; Back</button></a>

    {% if wishlist_products|length  != 0 %}
    <h6 class="ms-5">Item(s)</h6>
    <hr>

    {% for wishitem in wishlist_products %}
    <div class="row mb-5 d-flex">
        <div class="col">
            <img class="card-img-wishlist" src="{{ wishitem.product.image_url }}" alt="image"> 
        </div>
        <div class="col">
            <p class="fw-bold">{{wishitem.product.name}}</p>
        </div>
        <div class="col text-center">
            <p class="small">Unit price</p>
            <p class="small"> ${{ wishitem.product.price|currency:request.session.currency }} {{ request.session.currency }} </p>
        </div>
        <div class="col">
            <a href="{% url 'products:wishlist-delete' wishitem.product.id %}">
            <i class="bi bi-x-lg float-end"></i></a>
            <div class="align-items-center">
            <a class=" btn btn-dark align-self-center" href="">Add to cart</a>
            </div>
        </div>
    </div>
    {% endfor %}

    {% else %}
    <p class="text-center small"> Your don't have any items in your wish list. </p>
    {% endif %}
</div>
{% endblock content %}